### ISSUE TITLE
Server astro initialization failed on upgrade to v0.4

### ISSUE THREAD

**Issue by dawaltconley** [yaegassy/coc-astro#7]
First of all, thank you so much for this extension! It has definitely improved vim development in Astro for me.

I just tried upgrading to the latest version and the language server is failing to start. I assume this has something to do with v2 of the language server, since this extension works for me on v0.3.1 but breaks on v0.4.0.

Here's what I see after running `:CocInfo`:

```
## versions

vim version: VIM - Vi IMproved 8.2 8024919
node version: v16.18.1
coc.nvim version: 0.0.82-d938884d 2022-10-22 22:17:57 +0800
coc.nvim directory: /home/dawaltco/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2023-06-15T11:47:51.391 INFO (pid:325464) [configurations] - Add folder configuration from cwd: /home/dawaltco/Code/sites/portfolio/.vim/coc-settings.json
2023-06-15T11:47:51.513 INFO (pid:325464) [services] - registered service "stylelintplus"
2023-06-15T11:47:51.531 INFO (pid:325464) [plugin] - coc.nvim initialized with node: v16.18.1 after 81ms
2023-06-15T11:47:51.679 ERROR (pid:325464) [language-client-client] - Server astro initialization failed. vg [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:216:85329)
    at dd.handleConnectionClosed (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:221:10969)
    at dd.handleConnectionClosed (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:225:3553)
    at t (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:221:10621)
    at dP.invoke (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:23:14460)
    at Fc.fire (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:24:6501)
    at dP.invoke (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:23:14460)
    at Fc.fire (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2023-06-15T11:47:51.681 ERROR (pid:325464) [server] - unhandledRejection  Promise {
  <rejected> vg [Error]: Pending response rejected since connection got disposed
      at Object.dispose (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:50:4562)
      at Object.dispose (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:216:85329)
      at dd.handleConnectionClosed (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:221:10969)
      at dd.handleConnectionClosed (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:225:3553)
      at t (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:221:10621)
      at dP.invoke (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:23:14460)
      at Fc.fire (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:23:15230)
      at Re (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:24:6501)
      at dP.invoke (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:23:14460)
      at Fc.fire (/home/dawaltco/.vim/plugged/coc.nvim/build/index.js:23:15230) {
    code: -32097,
    data: undefined
  }
} vg [Error]: Pending response rejected since connection got disposed

...(errors repeat)...

2023-06-15T11:47:54.817 INFO (pid:325464) [attach] - receive notification: openList []
2023-06-15T11:47:58.647 INFO (pid:325464) [attach] - receive notification: showInfo []
```

**Comment by yaegassy** [comment]
I have found that the extension runs successfully when cloning the repository locally and building it, but when installing it using `CocInstall`, this error occurs.

I will find some time later to make the necessary adjustments.

**Comment by yaegassy** [comment]
Hi, @dawaltconley, Thank you once again for reporting the issue. 🙇

The adjustments have been completed. Please update `coc-astro` with `:CocUpdate` and check if the issue has been resolved.

**Comment by yaegassy** [comment]
It seems that the problem has been solved in my environment, so I will close this issue.

**Comment by dawaltconley** [comment]
Confirmed it's working on my end too. Thanks so much for the quick fix!
